spring:
  mvc:
    view:
      prefix: /html/
      suffix: .html
    # yml配置文件语法
    ##  1.key: value   k-v结构使用:号(空格)连接
    ##  2.YML配置文件有层级关系.
    ##  3.YML配置文件注意缩进.
    ##  4.YML文件支持中文.内部编码是utf-8编码
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8090
  # 设定项目发布路径
  servlet:
    context-path: /
    # /代表缺省值目录

# 在配置文件中添加属性和属性值,为了防止重名发生,则添加前缀区分
jdbc:
  username: root
  password: root



mybatis-plus:
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
